name: Android
on:
  workflow_dispatch:

jobs:
  android-emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils cpu-checker
          sudo apt-get install -y openjdk-17-jdk
          sudo apt-get install -y xfce4 xfce4-goodies
          sudo apt-get install -y tightvncserver

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Install Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          mkdir -p $HOME/android/sdk
          unzip cmdline-tools.zip -d $HOME/android/temp
          mv $HOME/android/temp/cmdline-tools $HOME/android/sdk/
          rm -rf $HOME/android/temp cmdline-tools.zip
          echo "export ANDROID_SDK_ROOT=$HOME/android/sdk" >> $HOME/.bashrc
          echo "export PATH=$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools" >> $HOME/.bashrc
          source $HOME/.bashrc
          
      - name: Download Android System Image and Tools
        run: |
          export PATH=$PATH:$HOME/android/sdk/cmdline-tools/bin
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "emulator" "system-images;android-33;google_apis;x86_64"

      - name: Create Android Emulator (AVD)
        run: |
          export PATH=$PATH:$HOME/android/sdk/cmdline-tools/bin
          echo "no" | avdmanager create avd -n android_vm -k "system-images;android-33;google_apis;x86_64" -d "pixel_6"
          
      - name: Start VNC Server
        run: |
          echo "password" | vncpasswd -f > $HOME/.vnc/passwd
          chmod 600 $HOME/.vnc/passwd
          vncserver :1 -geometry 1280x720 -depth 24
          
      - name: Start Emulator and Stream to VNC
        run: |
          export DISPLAY=:1
          export PATH=$PATH:$HOME/android/sdk/emulator
          nohup emulator -avd android_vm -no-snapshot -no-window -no-audio -camera-back none -camera-front none > emulator.log 2>&1 &

      - name: Establish Tailscale Connection
        run: |
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }} --hostname "github-android"
          echo "Tailscale IP: $(tailscale ip -4)"
          echo "VNC Password is: password"
          sleep infinity # Keep the runner alive
